Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20221029135357_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
=> made user devise model

Gemfile.lock, app/controllers/sneakers_controller.rb, test/controllers/sneakers_controller_test.rb
=> done sneakers controller

Gemfile, Gemfile.lock, app/models/sneaker.rb, app/models/user.rb, db/seeds.rb
=> seeded 1-user and 10-sneakers

app/views/layouts/application.html.erb, app/views/sneakers/index.html.erb, config/initializers/assets.rb
=> did view index

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/pages/_card.html.erb, app/views/pages/_navbar.html.erb
add some style, will fix when we have more information
=> style navbar and card

app/views/layouts/application.html.erb, app/views/sneakers/index.html.erb
check in index.html.erb this parshal
=> Order model

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/sneakers_controller.rb, app/models/sneaker.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/sneakers/_form.html.erb, app/views/sneakers/new.html.erb, app/views/sneakers/show.html.erb, config/initializers/devise.rb, config/routes.rb, db/migrate/202210291357_add_photos_to_sneakers.rb, db/migrate/20221101195228_add_photos_to_sneakers.rb, db/schema.rb
we did the log in and simple forms as usual
=> Simple forms

app/controllers/orders_controller.rb, app/controllers/sneakers_controller.rb, app/views/order/create.html.erb, app/views/sneakers/show.html.erb, config/routes.rb, db/migrate/20221103203204_remove_date_from_table_orders.rb, db/schema.rb, test/controllers/order_controller_test.rb
=> order-constroller, routes, show, remove-date form schema

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_grid.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_grid.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_search.html.erb, app/views/sneakers/index.html.erb
Made some changes to the layout and mainly improved the grid on the front page
=> Nav bar + layout

app/views/layouts/application.html.erb, app/views/sneakers/index.html.erb
fixed the grid render issue by moving to index
=> fixed grid render

app/controllers/sneakers_controller.rb
Anyone can now visit the homepage and see a show page without logging in - everything else requires sign in
=> done authentications

app/assets/stylesheets/components/_card.scss, app/controllers/orders_controller.rb, app/controllers/pages_controller.rb, app/views/orders/index.html.erb, app/views/shared/_grid.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
i change sebastian's photo to seekasneaker logo , added a drop down for adding new sneaker so i suggest we remove the button in the index that says list a sneaker. but didnt remove i wanted to ask for your thoughts first.
=> Icon photo change

app/controllers/pages_controller.rb, app/views/pages/my_sneakers.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> add sneakers list

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/views/orders/index.html.erb, app/views/shared/_navbar.html.erb
the past orders are done. exchange colours of the page. very subtle changes
=> past orders done, exchange colours of the pages to same

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_sneakers_list.scss, app/controllers/sneakers_controller.rb, app/views/pages/my_sneakers.html.erb, app/views/sneakers/edit.html.erb, config/routes.rb
Style sneaker list, added button "change" and link to edit form
=> edit sneakers list

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card_sneaker.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_grid.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_review_card.scss, app/assets/stylesheets/components/_search_form.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/reviews_controller.rb, app/controllers/sneakers_controller.rb, app/helpers/reviews_helper.rb, app/javascript/controllers/index.js, app/javascript/controllers/star_rating_controller.js, app/views/layouts/application.html.erb, app/views/orders/show.html.erb, app/views/reviews/index.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_grid.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_old-search.html.erb, app/views/sneakers/index.html.erb, app/views/sneakers/show.html.erb, db/seeds.rb, package.json, yarn.lock
- created reviews page and design tweaks elsewhere
=> Reviews page

app/assets/stylesheets/components/_card.scss, app/views/orders/index.html.erb
i have fixed the scrolling issues, added a button to go back to the home page
=> order-page improved page

app/assets/stylesheets/components/_navbar.scss, app/controllers/sneakers_controller.rb, app/views/shared/_navbar.html.erb, app/views/sneakers/_form.html.erb, db/migrate/20221129136764_add_size_to_sneakers.rb, db/schema.rb
=> added size

app/assets/stylesheets/components/_form.scss, app/views/sneakers/new.html.erb, db/schema.rb
=> form all centered

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_sneakers_list.scss, app/views/pages/my_sneakers.html.erb
=> fix css buttons
